### ISSUE TITLE
tSNE: clicking to hide cluster/metadata category freezes page on Chrome 87/macOS 

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#116] opened 2020-12-15 11:18 UTC
When clicking a cluster label or a metadata label as shown in the screenshot:

![image](https://user-images.githubusercontent.com/368478/102208264-182dc980-3ec7-11eb-838f-ab9d5cd24ba4.png)

The page freezes on Chrome/macOS and never recovers (you need to kill the tab). It has happened now with 3 different experiments, regardless of being cluster number of metadata label.

**Comment by alfonsomunozpomer** [comment] 2020-12-15 11:40
I’ve seen this happens on fairly sized clusters (not experiments, i.e. small clusters in big experiments perform well). E.g. https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-150728 cluster 7 is ok, cluster 1 is not. This is an issue in Highcharts’ being a black box since we use the default legend. I think we should disable the interactivity or verify this is resolved in the latest version. I’ll check their GitHub issues to see if this is documented.

**Comment by alfonsomunozpomer** [comment] 2021-08-17 17:56
I’m closing this issue because I can’t reproduce it anymore. I think Highcharts fixed this upstream (which is great, by the way).

**Closed by alfonsomunozpomer** 2021-08-17 17:56 UTC
