### ISSUE TITLE
Single cell experiment page link broken for the experiment - E-MTAB-7316

### ISSUE THREAD

**Issue by upendrakumbham** [ebi-gene-expression-group/atlas-web-single-cell#162] opened 2021-04-15 13:12 UTC
Issue: Experiments page has been broken for the experiment:  E-MTAB-7316

[E-MTAB-7316](http://ves-hx-77:8080/gxa/sc/experiments/E-MTAB-7316) - 400 error.

User ticket on RT:  https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=489128

Pivotal reference: https://www.pivotaltracker.com/story/show/177533187

**Comment by upendrakumbham** [comment] 2021-04-15 13:18
I have started my debugging to find a root cause:

I'm able to reproduce the bug. I could see '400' error code when I try to fetch the experiment: E-MTAB-7316 on `ves-hx-77`(test)

**Comment by upendrakumbham** [comment] 2021-04-15 13:25
During code debugging, I have seen Solr Exceptions while fetching experiment:

`Class - ExperimentController.java -> endpoint-> "/experiments/{experimentAccession}" method-> showExperimentPage(..)`

In this method, while adding content to the model code is failing.

```
...model.addAttribute(
                "content",
                experimentPageContentSerializer.experimentPageContentForExperiment(experimentAccession, accessKey));
```

**Comment by upendrakumbham** [comment] 2021-04-15 13:34
I have decided to switch test Solr to point to analytics v3 collection instead of v5 just to prove that collection issue or not.
I have created a new alias on [Test Solr](http://wp-p3s-67:8983/solr/#/~collections) and pointed to the `scxa-analytics-v3` collection from the` scxa-analytics-v5`.

**Comment by upendrakumbham** [comment] 2021-04-15 13:38
I have tested after pointing test Solr to v3 and found that the experiment page working fine for the experiment: E-MTAB-7316. I have got the `200` status code.

**Comment by upendrakumbham** [comment] 2021-04-16 05:23
Again I pointed [Test Solr](http://wp-p3s-67:8983/solr/#/~collections) to analytics v5 collection to find out java problematic a piece of code. Here are the details and exceptions traces...

Problematic java code -  
```

Class- CellMetaDataDao.java -> 

method->

// Given a type of metadata and an experiment accession, this method retrieves the value of that metadata for the
    // cells in an experiment
    public ImmutableMap<String, String> getMetadataValues(String experimentAccession,
                                                          String metadataType) {
        // Find matching characteristic name and factor name docs...
 var solrQueryBuilder =
                new SolrQueryBuilder<SingleCellAnalyticsCollectionProxy>()
                        .addQueryFieldByTerm(EXPERIMENT_ACCESSION, experimentAccession)
                        .addQueryFieldByTerm(ImmutableMap.of(
                                FACTOR_NAME, ImmutableSet.of(metadataType),
                                CHARACTERISTIC_NAME, ImmutableSet.of(metadataType)))
                        .sortBy(CELL_ID, asc)
                        .setFieldList(ImmutableSet.of(CELL_ID, FACET_CHARACTERISTIC_VALUE, FACET_FACTOR_VALUE));
........}
```
Here are the exception details throwing from this method:

```
Exception trace: org.apache.solr.common.SolrException: Could not load collection from ZK: scxa-analytics-v5
Code: 400

Detailed message: Could not load collection from ZK: scxa-analytics-v5
Path: /collections/scxa-analytics-v5/state.json

org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /collections/scxa-analytics-v5/state.json


java.io.IOException: --> http://10.3.10.103:8983/solr/scxa-analytics-v5_shard4_replica_n4/: An exception has occurred on the server, refer to server log for details.

java.io.IOException: org.apache.solr.common.SolrException: Could not load collection from ZK: bioentities
```
This bug is a bit tricky - the majority of the exceptions are related to `scxa-analytics-v5`, But I have noticed bioentities exceptions as well sometimes during debugging.

As we are using Solr streams to deal with Solr, I'm not really sure which line of code causing the issue in the above method. But I can say that after fetching metadata types, we are trying to fetch metadata values for each type. During that process, for the `metadata type = 'replicate'` Solr contact is failing.

**Comment by upendrakumbham** [comment] 2021-04-16 05:26
@lingyun1010 -Hope I have provided all the details that I found in my debugging to progress on this further.

**Comment by lingyun1010** [comment] 2021-04-16 07:09
Error is on the line in `CellMetadataService` class
```
cellMetadataDao.getCharacteristicTypes(experimentAccession).stream())
```

Error message is ```org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /collections/scxa-analytics-v5/state.json```

**Comment by lingyun1010** [comment] 2021-04-16 08:19
Error meesage: ` http://10.3.10.103:8983/solr/scxa-analytics-v5_shard4_replica_n4/: An exception has occurred on the server, refer to server log for details.`

Line 160: `        try (var tupleStreamer = TupleStreamer.of(uniqueStreamBuilder.build())) ` in `CellMetadataDao` class.

**Comment by lingyun1010** [comment] 2021-04-16 09:09
The error metadataType comes from `cellMetadataDao.getFactorTypes(experimentAccession).stream()` in `CellMetadataService` class.

The solution might be remove/filter the metadataType in return.

**Comment by upendrakumbham** [comment] 2021-04-16 09:31
Great, @lingyun1010. Will see, what @alfonsomunozpomer or @pcm32 suggest on this.

**Comment by pcm32** [comment] 2021-04-16 13:22
Great debugging issue @upendrakumbham and @lingyun1010! This is very useful. What puzzles me still is why this error only comes up in the servers but not on your dev environments.... this also makes sense with the pattern that we saw in the past when loading data into solr for v5: it worked fine from laptops but failed from servers (and we could never figure out the issue - it went away when Alfonso replicated test solr into dev solr I think).

**Comment by upendrakumbham** [comment] 2021-04-19 09:11
Hi @pcm32, last Friday @alfonsomunozpomer also joined us to debug this tricky bug, under his guidance we got more insights about the bug, but we didn't find the exact root cause why Solr `TupleStreamer` throwing `UncheckedIOException`.
We are planning to continue our debugging today with @alfonsomunozpomer to fix this bug as soon as possible.

**Comment by lingyun1010** [comment] 2021-05-17 11:49
Please debug the line `cellMetadataDao.getMetadataValues(experimentAccession, metadataType);` with `metadataType` in the experiment E-MTAB-7316
```
0 = "replicate"
1 = "individual"
2 = "sex"
3 = "inferred_cell_type_-_authors_labels"
4 = "inferred_cell_type_-_ontology_labels"
```

**Comment by pcm32** [comment] 2021-05-25 13:58
I suspect, based on logs, that E-ENAD-51 and E-ENAD-53 are suffering from the same.

```
14:50:55.134 [http-nio-8080-exec-83] INFO  uk.ac.ebi.atlas.web.interceptors.TimingInterceptor - /gxa/sc/experiments/E-ENAD-51?accesskey=c2d37860-f2f5-40bc-b60b-ae55cd4c63b5 - start
14:50:55.567 [http-nio-8080-exec-83] INFO  uk.ac.ebi.atlas.solr.cloud.CollectionProxy - Querying *:*
14:50:55.579 [http-nio-8080-exec-83] INFO  uk.ac.ebi.atlas.solr.cloud.CollectionProxy - Querying characteristic_name:("inferred_cell_type_\-_ontology_labels")
14:50:56.245 [http-nio-8080-exec-83] ERROR uk.ac.ebi.atlas.controllers.HtmlExceptionHandlingController - null -
```

**Comment by pcm32** [comment] 2021-05-28 08:49
@lingyun1010 @upendrakumbham @alfonsomunozpomer do we know if the issue is exactly the same across all experiments, or could it be that it is different pieces in the content brought by the solr query that could be generating this?

**Comment by alfonsomunozpomer** [comment] 2021-06-07 16:00
@lingyun1010 @upendrakumbham Many thanks for your comments and insights, it’s been very helpful and you were close to solving the mystery!

The issue is that in all these experiments there are cells that are missing the `inferred cell type - authors labels` field in Solr. This happens only in `scxa-analytics-v5`. For instance:
- E-MTAB-7316: ERR2854358-AAACCTGAGAGGTAGA

This doesn’t match the condensed SDRF file, which has a value for the authros labels.

Looking at E-HCAD-5 and faceting over `facet_factor_name`, [we’ve got in v3](http://wp-p3s-66:8983/solr/scxa-analytics-v3/select?facet.field=facet_factor_name&facet=on&q=experiment_accession:%22E-HCAD-5%22&rows=0):
```
"facet_factor_name":[
        "cell_type",23474,
        "inferred_cell_type_-_authors_labels",17542,
        "inferred_cell_type_-_ontology_labels",17542,
        ...
```

And [in v5 we have](http://wp-p3s-66:8983/solr/scxa-analytics-v5/select?facet.field=facet_factor_name&facet=on&q=experiment_accession:%22E-HCAD-5%22&rows=0):
```
"facet_factor_name":[
        "cell_type",23572,
        "inferred_cell_type_-_authors_labels",17499,
        "inferred_cell_type_-_ontology_labels",17465,
        ...
```

Again, this doesn’t match the condensed SDRF file:
```bash
[tc_fg02@ves-hx-77 E-HCAD-5]$ grep "inferred cell type - authors labels" E-HCAD-5.condensed-sdrf.tsv | wc -l
17542
[tc_fg02@ves-hx-77 E-HCAD-5]$ grep "inferred cell type - ontology labels" E-HCAD-5.condensed-sdrf.tsv | wc -l
17542
```

This isn’t a comprehensive list, but I’d bet a beer that this is in fact the problem. Somewhere along the code this breaks some expectation or implicit assumption (from the looks of it, `CellMetadataDao`).

Now, we need to decide what we should do:
1. Fail gracefully and show data as it is from Solr, and ["we do the best we can with what we have"](https://www.youtube.com/watch?v=StDCqrxrdHY&t=77s).
2. Show a meaningful error that will help us fix the error.

**Comment by pcm32** [comment] 2021-06-08 08:05
I'm guessing the question is why we have different numbers of elements loaded in Solr compared to the condensed, since the analytics index gets loaded from the condensed, and that process runs every time that the condensed get modified. We will need to check the loading. Or could this be somehow related to the ontology expansion?

Does the web application has any awareness on whether it is deployed on wwwdev or www? It would be great if in public it could just show what we find (option 1) and in the wwwdev do 1 as well but also show the message suggested in 2 for ourselves.

Could you please generate a list from Solr of the cell types with the 3 annotations for one of the experiments, so that we can compare the missing ones with the condensed and see whether there is any pattern in the data that can unravel the source of this disparity? Thanks!

**Comment by alfonsomunozpomer** [comment] 2021-06-08 09:49
The missing docs isn’t related to ontology expansion, or it shouldn’t be, since the document makes it to Solr and then BioSolr adds the missing fields. Of course, I don’t know if an exception in the ontology expansion process could prevent a document from getting into the collection, but I doubt it. A simple way of knowing for sure would be to inspect the JSON files before sending them to Solr. It‘d be easy to do with a very simple edit in our scripts and running it for one of these faulty experiments.

As for your second question the answer is no. The app is the same in both staging and public/fallback (this is a desirable feature). What we should do is to add logging messages in the code and produce warning messages that we can easily grep from the log files. If I’m not mistaken, the only difference in logging between staging and public/fallback is that in the latter logs are written in batches instead of line-by-line to decrease I/O waiting times. The logging configuration is injected when Tomcat deploys the app in the file `logback.xml` and is located together with `jdbc.properties` and `solr.properties`.

I’ll do the list for E-HCAD-5. It shouldn’t be hard with a bit of `jq` and `comm`.

**Comment by pcm32** [comment] 2021-06-08 10:35
For the E-MTAB-7316 cell mentioned, doing:

```
awk -F'\t' 'BEGIN { OFS = "\t"; } { if( $4 == "factor" || $4 == "characteristic" ) { gsub(/ /, "_", $5); print "{ \"experiment_accession\": \""$1"\",\n \"cell_id\": \""$3"\",\n \""$4"_name\": \""$5"\",\n \""$4"_value\": [\""$6"\"],\n \"ontology_annotation\": [\""$7"\"] }"; } }' E-MTAB-7316.condensed-sdrf.tsv |jq -s '. | del(.[][] | select(. == [""]))' | grep -A 5 -B 2 ERR2854358-AAACCTGAGAGGTAGA
```

in the ATLAS_SC_EXPERIMENTS/E-MTAB-7316 directory you get:

```
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "developmental_stage",
    "characteristic_value": [
      "adult"
    ],
    "ontology_annotation": [
--
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "disease",
    "characteristic_value": [
      "normal"
    ],
    "ontology_annotation": [
--
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "individual",
    "characteristic_value": [
      "Donor 1 [17-010]"
    ]
  },
--
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "organism",
    "characteristic_value": [
      "Homo sapiens"
    ],
    "ontology_annotation": [
--
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "organism_part",
    "characteristic_value": [
      "retinal neural layer"
    ],
    "ontology_annotation": [
--
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "replicate",
    "characteristic_value": [
      "5"
    ]
  },
--
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "sex",
    "characteristic_value": [
      "female"
    ],
    "ontology_annotation": [
--
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "factor_name": "replicate",
    "factor_value": [
      "5"
    ]
  },
--
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "factor_name": "inferred_cell_type_-_ontology_labels",
    "factor_value": [
      "retinal rod cell"
    ]
  },
--
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "factor_name": "inferred_cell_type_-_authors_labels",
    "factor_value": [
      "retinal rod cell CCA1"
    ]
  },
```

which looks alright to me. This is the same as running:

```
condSdrf2tsvForSCXAJSONFactorsIndex.sh $CHUNK_FILE | jsonFilterEmptyFields.sh 
```

so everything before the loading.

**Comment by pcm32** [comment] 2021-06-08 11:29
A cleaner version of this which could be used to attempt a loading into solr (to see why it doesn't load):

```bash
cat E-MTAB-7316.condensed-sdrf.tsv | grep 'ERR2854358-AAACCTGAGAGGTAGA' | awk -F'\t' 'BEGIN { OFS = "\t"; } { if( $4 == "factor" || $4 == "characteristic" ) { gsub(/ /, "_", $5); print "{ \"experiment_accession\": \""$1"\",\n \"cell_id\": \""$3"\",\n \""$4"_name\": \""$5"\",\n \""$4"_value\": [\""$6"\"],\n \"ontology_annotation\": [\""$7"\"] }"; } }' | jq -s '. | del(.[][] | select(. == [""]))'
```

which yields:

```json
[
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "developmental_stage",
    "characteristic_value": [
      "adult"
    ],
    "ontology_annotation": [
      "http://www.ebi.ac.uk/efo/EFO_0001272"
    ]
  },
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "disease",
    "characteristic_value": [
      "normal"
    ],
    "ontology_annotation": [
      "http://purl.obolibrary.org/obo/PATO_0000461"
    ]
  },
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "individual",
    "characteristic_value": [
      "Donor 1 [17-010]"
    ]
  },
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "organism",
    "characteristic_value": [
      "Homo sapiens"
    ],
    "ontology_annotation": [
      "http://purl.obolibrary.org/obo/NCBITaxon_9606"
    ]
  },
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "organism_part",
    "characteristic_value": [
      "retinal neural layer"
    ],
    "ontology_annotation": [
      "http://purl.obolibrary.org/obo/UBERON_0003902"
    ]
  },
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "replicate",
    "characteristic_value": [
      "5"
    ]
  },
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "characteristic_name": "sex",
    "characteristic_value": [
      "female"
    ],
    "ontology_annotation": [
      "http://purl.obolibrary.org/obo/PATO_0000383"
    ]
  },
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "factor_name": "replicate",
    "factor_value": [
      "5"
    ]
  },
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "factor_name": "inferred_cell_type_-_ontology_labels",
    "factor_value": [
      "retinal rod cell"
    ]
  },
  {
    "experiment_accession": "E-MTAB-7316",
    "cell_id": "ERR2854358-AAACCTGAGAGGTAGA",
    "factor_name": "inferred_cell_type_-_authors_labels",
    "factor_value": [
      "retinal rod cell CCA1"
    ]
  }
]
```

maybe someone can try loading this into solr and see if it goes through?

**Comment by alfonsomunozpomer** [comment] 2021-07-27 11:03
Fixed by https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/185.

**Closed** 2021-07-27 11:03 UTC
