### ISSUE TITLE
Lung anatomogram doesn't show heatmap entering alveolus cross-section (even though there is data)

### ISSUE THREAD

**Issue by anjaf** [ebi-gene-expression-group/atlas-web-single-cell#133] opened 2021-01-25 12:21 UTC
One weird behaviour I noticed is the following in lung:
https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-GEOD-130148/results/anatomogram
Going deeper through the zoom ins, results in the heatmap disappear and then appear again. 
Click through to the alveolus cross section, I see the heat map showing "no results" but the 2 cell types are highlighted and hoverable. When I click on the shape, the corresponding expression appears. 
So in the previous image I saw the 2 cell types in the heat map, clicked on the zoom in to the alveolus cross section, they disappeared, but selecting a particular cell type brings up results from the empty heat map.

Before entering the zoom-in (data in the heatmap):
![Screenshot 2021-01-25 at 12 19 31](https://user-images.githubusercontent.com/18234138/105705092-9b4f3000-5f07-11eb-83f8-b7e319e33cad.png)

Entering cross section (no results):
![Screenshot 2021-01-20 at 09 58 15](https://user-images.githubusercontent.com/18234138/105704471-c2593200-5f06-11eb-9539-e38246b8bc61.png)

After clicking on cell type (results in the heatmap):
![Screenshot 2021-01-20 at 09 58 26](https://user-images.githubusercontent.com/18234138/105704565-e87ed200-5f06-11eb-85c0-3280e4adebd4.png)

I don't know if that is the intended behaviour but I would have expected the results not to disappear when selecting the zoom in for the cell types that have their shape in the zoom in and data available.

**Comment by alfonsomunozpomer** [comment] 2021-02-03 08:51
Duplicate of https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/121.

**Closed by alfonsomunozpomer** 2021-02-03 08:51 UTC
