### ISSUE TITLE
No cell type heatmap shown for images with active anatomogram cell types

### ISSUE THREAD

**Issue by sfexova** [ebi-gene-expression-group/atlas-web-single-cell#130] opened 2021-01-21 15:17 UTC
e.g. here:
https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-1/results/anatomogram - if you click your way down to the alveolus x-section image (screenshot below) there is no heatmap with cell types, even though we do have the data for at least some of them
<img width="1881" alt="Screen Shot 2021-01-21 at 15 07 29" src="https://user-images.githubusercontent.com/30924848/105370315-61c2b000-5bfb-11eb-844c-4d10bfb97189.png">

<img width="1901" alt="Screen Shot 2021-01-21 at 15 07 48" src="https://user-images.githubusercontent.com/30924848/105370366-6b4c1800-5bfb-11eb-8f8f-708ecc14c4de.png">

all of the cell types appear (not just the ones included relevant for the particular zoom-in) once you select one cell type (second screenshot) but for pancreas for example, you can see the cell type marker map even without selecting one particular cell type. The user should definitely be able to see something when jumping into a zoom-in with some active shapes - ideally a filtered heat map with just the relevant cell types but as a quick fix whole heatmap would be OK for now too

**Comment by pcm32** [comment] 2021-01-22 11:50
this is a duplicate of #121 as far as I can tell.

**Comment by sfexova** [comment] 2021-01-22 12:12
oh, yes, sorry - didn't notice you'd already mentioned this issue - should I close this one then?

**Comment by pcm32** [comment] 2021-01-22 12:33
No problem, I guess we can. I just meant to link the two (so now this one is visible from the other).

**Closed by pcm32** 2021-01-22 12:33 UTC
