### ISSUE TITLE
Icon to go back to previous zoom level doesn't work on certain ocassions

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#142] opened 2021-01-25 17:06 UTC
Reported by Nancy and others:

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-MTAB-5061/results/anatomogram
Tooltip to upper image doesn’t work. 
Can't find cell type images for type B cells.
Can we make it so that when you hover over a shape in the anatomogram a tooltip pops up with the shape name even when the shape is white?

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-GEOD-81608/results/anatomogram
tooltip back up doesn’t work

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-9/results/anatomogram
tooltip to upper image doesn’t work
Cell types are defined in the heatmap (stellate cel) that aren't coloured in in the anatomogram

https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-8/results/anatomogram
tooltip to upper image doesn’t work
no cell type shapes found in zoom ins

**Comment by pcm32** [comment] 2021-01-25 17:21
Example from Anja:

3. Does clicking the parent icon bring you back to the parent view? 
No, for lung, pancreas. 
Clicking the parent image does not bring back the previous view. Not even clicking no the "Anatomograms" tab on the left brings back the primary view. 
Tested e.g. here: https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-10/results/anatomogram

Partly no for liver, kidney. 
Page loads in the zoom in. The first click brings me back to the parent view. But after that when zooming in again, the click on the icon does not bring me back.

**Comment by pinin4fjords** [comment] 2021-01-25 17:44
Duplicate of: https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/134

**Comment by pcm32** [comment] 2021-02-02 12:55
Stories (albeit private to the world): 
https://www.pivotaltracker.com/story/show/176761819

**Comment by alfonsomunozpomer** [comment] 2021-02-05 20:59
> Can't find cell type images for type B cells

Yes, this is the test environment and data is patchy, maybe after all the troubles we had with v3 of the collection. FWIW, I’ve made `www-test` work against the latest Atlas ontology (**not EFO**) and we get correct results. I think we should rebuild the `scxa-analytics`.

**Comment by alfonsomunozpomer** [comment] 2021-02-05 21:00
> Can we make it so that when you hover over a shape in the anatomogram a tooltip pops up with the shape name even when the shape is white?

This is a feature, not a bug (and a design decision). The shape isn’t displayed, so we can’t show a tooltip. Unless we want to show the shapes in e.g. some dimmed grey colour by default.

**Comment by alfonsomunozpomer** [comment] 2021-02-05 21:02
I’m closing this issue, but if you have any remaining issues feel free to reopen it.

**Closed by alfonsomunozpomer** 2021-02-05 21:02 UTC
Labels: bug, in-pivotal
