### ISSUE TITLE
Liver ontology expansion for colouring of anatomogram shapes/structures

### ISSUE THREAD

**Issue by sfexova** [ebi-gene-expression-group/atlas-web-single-cell#129] opened 2021-01-21 14:56 UTC
cell type shapes/parent structures not active (grey) for matching cell types and theIr parent structure (liver lobule):
https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-9/results/anatomogram

cholangiocyte, Kupffer cell, hepatic stellate cell, both the sinusoidal endothelial cell types and the portal endothelial cell all should have a corresponding shape in the anatomogram highlighted as well as the parent structure (liver lobule) in the level-up (main image)
e.g. https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_1000488

**Comment by alfonsomunozpomer** [comment] 2021-02-03 09:39
Duplicate of https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/128.

**Closed by alfonsomunozpomer** 2021-02-03 09:39 UTC
Labels: bug, enhancement

**Comment by sfexova** [comment] 2021-02-08 19:52
hi! - so I had a look at dev again and we're still not seeing all the cell types we should see highlighted:
cholangiocyte, Kupffer cell, hepatic stellate cell, both the sinusoidal endothelial cell types and the portal endothelial cell all should have a corresponding shape in the anatomogram highlighted
this is not just a duplicate of #128 - which is mainly about retrieval of parent terms  (although we have that problem here too) - but here we do not have even the direct matches highlighted - e.g. we have data annotated as 'Kupffer cell' and there is 'Kupffer cell' shape in the anatomogram (tagged with the relevant ontology ID and label), but it's not highlighted. Same for all the other cell types I mentioned above too
https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-9/results/anatomogram

**Comment by alfonsomunozpomer** [comment] 2021-02-08 22:51
@sfexova Could you please let us know if this is the case in the test environment?
https://www-test.ebi.ac.uk/gxa/sc/experiments/E-HCAD-9/results/anatomogram

**Comment by sfexova** [comment] 2021-02-09 08:41
@alfonsomunozpomer Apologies! works great in test, all cell types highlighted as they should be. (Colouring of the parent structure - liver lobule, the tiny hegagons - in the level-up image structure doesn't but that's a different story, same as 128, like you said).
