### ISSUE TITLE
Unable to revert to top-level of anatomogram if no cell type has been clicked

### ISSUE THREAD

**Issue by pinin4fjords** [ebi-gene-expression-group/atlas-web-single-cell#134] opened 2021-01-25 12:44 UTC
This works: 

1. Go to https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-GEOD-81547/results/anatomogram
2. Click box to expand to detailed view
3. Click cell type
4. Click anatomogram to revert to wide ciew

But if you omit step 3, step 4 does not work and you can't get back to the wider view without refreshing the page.

**Comment by pinin4fjords** [comment] 2021-01-25 13:20
Particularly problematic e.g. here: https://wwwdev.ebi.ac.uk/gxa/sc/experiments/E-HCAD-8/results/anatomogram, i.e. where there are no cell types to click and therefore no way of going back up.

**Comment by alfonsomunozpomer** [comment] 2021-02-03 08:52
Duplicate of https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/142.

**Closed by alfonsomunozpomer** 2021-02-03 08:52 UTC
