### ISSUE TITLE
[anatomograms] Kupffer cells and others not appearing in liver anatomogram

### ISSUE THREAD

**Issue by sfexova** [ebi-gene-expression-group/atlas-web-single-cell#275] opened 2022-07-25 19:20 UTC
Kupffer cell not displayed in anatomograms in both these exp:

https://www.ebi.ac.uk/gxa/sc/experiments/E-HCAD-9/results/anatomogram
https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-10553/results/anatomogram

E-HCAD-9 additionally missing:
'endothelial cell of periportal hepatic sinusoid' aka 'periportal hepatic sinusoidal endothelial cell' (~old EFO term)
'endothelial cell of pericentral hepatic sinusoid' aka 'central venous hepatic sinusoidal endothelial cell' (~old EFO term)
> these two terms are among those updated in the anatomograms svg due to EFO terms being retired and replaced by new CL terms but the edit was done to be backwards compatible and the corresponding shapes thus should be displayed

Kupffer cell has not changed (neither term label nor ontology ID) so no idea why that has disappeared

**Comment by sfexova** [comment] 2022-07-25 19:23
btw 'endothelial cell of hepatic portal vein' previously labelled as 'portal endothelial cell' was also part of this same update and that has apparently worked fine and displays as it should in E-HCAD-9

**Comment by pcm32** [comment] 2022-08-02 07:46
I'm going to close this one as it is a duplicate of #267 , but this issue is linked there, so all the insights added here can be seen from the other one :-).

**Closed as completed by pcm32** 2022-08-02 07:46 UTC
