### ISSUE TITLE
experiment accession number gets cropped sometimes in cell type wheel marker gene table

### ISSUE THREAD

**Issue by sfexova** [ebi-gene-expression-group/atlas-web-single-cell#252] opened 2022-06-07 06:53 UTC
e.g. here: E-GEOD-135922 is cropped to just E-GEOD-1359 on the side:
<img width="738" alt="Screenshot 2022-06-07 at 07 54 13" src="https://user-images.githubusercontent.com/30924848/172315291-3ff0a5a8-9f04-4b23-8d71-ad6e9dfc0880.png">

**Comment by pcm32** [comment] 2022-06-07 12:05
We suspect that as we move these accessions to links, this might be resolved. We could attempt to give more space, but we think that as long as the link is correct this is alright-ish. This is because this means to take space from the heatmap as well.

**Comment by sfexova** [comment] 2022-06-07 12:08
then I suggest to do 'controlled cropping' - if the whole number doesn't fit, crop it but make it obvious it is cropped like 'E-GEOD-135...' or something

**Comment by pcm32** [comment] 2022-06-07 12:09
Could we do some angled labels (as in rotating the labels 30º or 45º) here maybe @alfonsomunozpomer ? that could also help in getting the accessions completely. Also the controlled cropping is a good idea.

**Comment by alfonsomunozpomer** [comment] 2022-06-27 07:03
We had previously agreed to remove the labels to the right of the heatmap, and it’s showing due to a regression in the code. This has been fixed in https://github.com/ebi-gene-expression-group/atlas-components/pull/115.

**Closed as completed by alfonsomunozpomer** 2022-06-27 07:03 UTC
