### ISSUE TITLE
Metadata search: Hint to the users that conditions can be searched now

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-single-cell#246] opened 2022-06-01 07:51 UTC
In the main search we currently see:

![image](https://user-images.githubusercontent.com/368478/171353946-d26d227f-3360-4a55-b643-556f7d033d4f.png)

I would expect this to hint currently that not only Gene IDs or symbols can be searched for, but also conditions and cell types. So maybe "Gene ID, gene symbol, cell type or condition/factor" and possibly expand examples below (I would love to see for instance as example "epithelial cell of lung") which should take us to datasets that also have anatomograms. Maybe the curators can suggest more example to put below.

**Comment by sfexova** [comment] 2022-06-06 13:39
Or maybe we could go with sth like 'Search genes (symbol or ID) and metadata (cell type, organism part, disease etc.)' and then have various examples underneath.
Another option as @ngeorgeebi suggested would be to have just search there and rely on the examples beneath to give people hints about what they can search for.

**Comment by anjaf** [comment] 2022-06-06 13:58
My suggestion would be to keep "biological condition" as term as it is called in bulk Atlas, so something like `Gene ID/symbol or biological condition (e.g. cell type, disease)`

Silvie's suggestion is also good as these are the category names in the dropdown. But I would change "and" to "or" because you can't search both at the same time. 

As examples we could use `keratinocyte`, `liver` and `lung cancer`

**Comment by pcm32** [comment] 2022-06-07 11:28
Initially we agreed with developers to:

- Use Nancy's solution of just having search (so no more "Gene ID or gene symbol").
- Provide the additional examples mentioned above.

**Comment by sfexova** [comment] 2022-06-07 11:34
I wouldn't use lung cancer as an example at this point though, it's giving a bit weird results (retina cells, 'not available' for cell types) - I made a ticket about it
maybe 'diabetes mellitus' or 'COVID-19'

**Comment by alfonsomunozpomer** [comment] 2022-06-30 20:03
Duplicate of #262. We’re in the process of streamlining our workflow with GitHub issues and this should be the original one pointed by the PR. Sorry for that!

**Closed as completed by alfonsomunozpomer** 2022-06-30 20:03 UTC
